packetdrill: suppress warning address-of-packed-member on tcp timestamp
Packetdrill needs to read and write possibly unaligned fields inside
tpc headers.

The actual unaligned accesses are safe, using unaligned_be32 helpers.
Recent versions of GCC start warning about the pointers to these
fields, which causes build failure due to -Werror.

These pointers are safe as the users all use the unaligned helpers.
Suppress this specific instance of this warning:

"
run_packet.c: In function ‘find_tcp_timestamp’:
run_packet.c:408:13: error: taking address of packed member of ‘struct tcp_option’ may result in an unaligned pointer value []
  408 |     (void *)&(option->data.time_stamp.val);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
run_packet.c:410:13: error: taking address of packed member of ‘struct tcp_option’ may result in an unaligned pointer value []
  410 |     (void *)&(option->data.time_stamp.ecr);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
"

Signed-off-by: Willem de Bruijn <willemb@google.com>