net-test: packetdrill: run_system_call: fix 32 bit builds
When building for arm32 the following error shows up:

run_system_call.c: In function 'cmsg_expect_eq':
run_system_call.c:860:38: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'size_t' {aka 'unsigned in
t'} [-Werror=format=]
  860 |      "Bad len in cmsg %d: expected=%lu actual=%lu",
      |                                    ~~^
      |                                      |
      |                                      long unsigned int
      |                                    %u
  861 |      i, ecm->cmsg_len, acm->cmsg_len);
      |         ~~~~~~~~~~~~~

run_system_call.c:3129:6: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'uint64_t' {aka 'long long
 unsigned int'} [-Werror=format=]
 3129 |      "epoll_event->data does not match script: "
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
......
 3133 |      event_live->data.u64);
      |      ~~~~~~~~~~~~~~~~~~~~

To fix these use %zu instead of %lu for size_t, and for the uint64_t use
%PRIu64 instad of %lu.

Reported-by: Naresh Kamboju <naresh.kamboju@linaro.org>
Signed-off-by: Anders Roxell <anders.roxell@linaro.org>