net-test: packetdrill: run_system_call: splice expects a pointer to the offset
It appears that the previous code cannot possibly work correctly, but I
could not produce any failure without this patch.
However, when building for arm32 bit, the following error shows up:

run_system_call.c: In function 'syscall_splice':
run_system_call.c:3250:31: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
 3250 |   result = splice(fd_in_live, (loff_t *) off_in, fd_out_live,
      |                               ^
run_system_call.c:3251:5: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
 3251 |     (loff_t *) off_out, len, flags);
      |     ^
cc1: all warnings being treated as errors
make: *** [<builtin>: run_system_call.o] Error 1

The man pages for splice says that splice expects a pointer to the
offset. This is done for ifc.splice. Doing the same for splice.

Reported-by: Naresh Kamboju <naresh.kamboju@linaro.org>
Signed-off-by: Anders Roxell <anders.roxell@linaro.org>