packetdrill: run_all: avoid error in case of timeout
When a test is blocked and after a timeout, this Python error is
produced:

  Exception in thread Thread-1:
  Traceback (most recent call last):
    File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
      self.run()
    File "packetdrill/run_all.py", line 169, in run
      self.testset.RunDir(self.path)
    File "packetdrill/run_all.py", line 147, in RunDir
      self.PollTestSet(procs, time_start)
    File "packetdrill/run_all.py", line 136, in PollTestSet
      for proc, path, variant in procs:
  ValueError: too many values to unpack (expected 3)

That's simply because 'procs' variable is an array of tuple containing
5 items. Two additional items are missing: stdout and stderr.

With the patch, we have a clearer error:

  KILL [/opt/packetdrill/gtests/net/mptcp/mp_join/mp_join_client.pkt (ipv4)]

Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>